/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 318 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 2 "hello.c"
int main(void) 
{ 


  {
#line 2
  printf("enter main\n");
  {
#line 4
  printf("call printf\n");
#line 4
  printf((char const   * __restrict  )"Hello, World!");
#line 4
  printf("return from printf\n");
  {
#line 5
  printf("exit main\n");
#line 5
  return (0);
  }
  }
}
}
