/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 318 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 5 "lib.c"
void vtrace0(int a , int b ) 
{ 


  {
#line 6
  printf((char const   * __restrict  )"done! %d - %d\n", a, b);
#line 7
  return;
}
}
