/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 318 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 2 "test2.c"
int g  =    0;
#line 4 "test2.c"
int plus(int a , int b ) 
{ 


  {
#line 8
  return (a + b);
}
}
#line 11 "test2.c"
int main(void) 
{ 
  int x ;
  int y ;
  int res ;
  int tmp ;

  {
#line 12
  x = 1;
#line 12
  y = 3;
#line 13
  tmp = plus(x, y);
#line 13
  res = tmp;
#line 14
  printf((char const   * __restrict  )"res: %d + %d = %d\n", x, y, res);
#line 15
  return (0);
}
}
