/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 4 "test7.c"
int main(void) 
{ 
  int x ;
  int y ;

  {
#line 6
  while (1) {
    vtrace0(x, y);
#line 6
    if (! (x < y)) {
#line 6
      break;
    }
#line 7
    x --;
#line 8
    while (1) {
      vtrace0(x);
#line 8
      if (! (x < 5)) {
#line 8
        break;
      }
#line 9
      x ++;
    }
  }
#line 12
  return (0);
}
}
