/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 3 "test9.c"
void vtrace2(int a , int b ) 
{ 


  {
#line 3
  return;
}
}
#line 6 "test9.c"
int main(void) 
{ 
  int x ;
  int y ;

  {
#line 7
  x = 3;
#line 7
  y = 1;
  {
#line 9
  while (1) {
    vtrace2(x, y);
#line 9
    if (! (x > y)) {
#line 9
      break;
    }
#line 10
    x --;
  }
  }
#line 12
  return (0);
}
}
