/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 318 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 3 "test1.c"
int plusone(int a ) 
{ 
  int b ;

  {
#line 5
  b = a + 1;
#line 6
  return (b);
}
}
#line 9 "test1.c"
int main(void) 
{ 
  int num ;

  {
#line 10
  num = 10;
#line 11
  num = plusone(num);
#line 12
  printf((char const   * __restrict  )"num = %d\n", num);
#line 13
  return (0);
}
}
