/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 318
extern int printf(char const   * __restrict  __format  , ...) ;
#line 3 "test8.c"
int g  =    2;
#line 5 "test8.c"
void f(void) 
{ 
  int d ;

  {
#line 6
  d = 1;
#line 7
  return;
}
}
#line 9 "test8.c"
int main(void) 
{ 
  int x ;
  int y ;
  int z ;

  {
#line 10
  x = 3;
#line 10
  y = 1;
#line 11
  printf((char const   * __restrict  )"hi\n");
  {
#line 12
  while (1) {
    vtrace1(x, y);
#line 12
    if (! (x > y)) {
#line 12
      break;
    }
#line 13
    x --;
  }
  }
#line 15
  z = 0;
  {
#line 15
  while (1) {
    vtrace1(z);
#line 15
    if (! (z < 2)) {
#line 15
      break;
    }
#line 16
    printf((char const   * __restrict  )"%d\n", z);
#line 15
    z ++;
  }
  }
#line 18
  return (0);
}
}
