/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 318 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 4 "test5.c"
int plus(int a , int b ) ;
#line 3 "test5.c"
int plusone(int c ) 
{ 
  int d ;
  int tmp ;

  {
#line 4
  tmp = plus(c, 1);
#line 4
  d = tmp;
#line 5
  return (d);
}
}
#line 7 "test5.c"
int plus(int a , int b ) 
{ 


  {
#line 9
  return (a);
}
}
#line 12 "test5.c"
int main(void) 
{ 
  int x ;
  int res ;
  int tmp ;

  {
#line 13
  x = 4;
#line 14
  tmp = plusone(x);
#line 14
  res = tmp;
#line 15
  printf((char const   * __restrict  )"res: %d + 1 = %d\n", x, res);
#line 16
  return (0);
}
}
