/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 318
extern int printf(char const   * __restrict  __format  , ...) ;
#line 3 "test10.c"
int main(void) 
{ 
  int i ;
  int k ;
  float j ;
  int loop_count ;

  {
#line 5
  i = 0;
#line 5
  k = 0;
#line 6
  j = (float )0;
#line 7
  loop_count = 5;
#line 9
  printf((char const   * __restrict  )"Case1:\n");
#line 10
  i = 0;
  {
#line 10
  while (1) {
    vtrace0(i, loop_count);
#line 10
    if (! (i < loop_count)) {
#line 10
      break;
    }
#line 11
    printf((char const   * __restrict  )"%d\n", i);
#line 10
    i ++;
  }
  }
#line 14
  printf((char const   * __restrict  )"Case2:\n");
#line 15
  j = (float )5.5;
  {
#line 15
  while (1) {
    vtrace0(j);
#line 15
    if (! (j > (float )0)) {
#line 15
      break;
    }
#line 16
    printf((char const   * __restrict  )"%f\n", (double )j);
#line 15
    j -= (float )1;
  }
  }
#line 19
  printf((char const   * __restrict  )"Case3:\n");
#line 20
  i = 2;
  {
#line 20
  while (1) {
    vtrace0(i);
#line 20
    if (i < 5) {
#line 20
      if (! (i >= 2)) {
#line 20
        break;
      }
    } else {
#line 20
      break;
    }
#line 21
    printf((char const   * __restrict  )"%d\n", i);
#line 20
    i ++;
  }
  }
#line 24
  printf((char const   * __restrict  )"Case4:\n");
#line 25
  i = 0;
  {
#line 25
  while (1) {
    vtrace0(i);
#line 25
    if (! (i != 5)) {
#line 25
      break;
    }
#line 26
    printf((char const   * __restrict  )"%d\n", i);
#line 25
    i ++;
  }
  }
#line 29
  printf((char const   * __restrict  )"Case5:\n");
#line 31
  i = 0;
  {
#line 31
  while (1) {
    vtrace0(i, loop_count);
#line 31
    if (! (i < loop_count)) {
#line 31
      break;
    }
#line 31
    i ++;
  }
  }
#line 33
  printf((char const   * __restrict  )"Case6:\n");
#line 34
  i = 0;
#line 34
  k = 0;
  {
#line 34
  while (1) {
    vtrace0(i);
#line 34
    if (i < 5) {
#line 34
      if (! (k < 3)) {
#line 34
        break;
      }
    } else {
#line 34
      break;
    }
#line 35
    printf((char const   * __restrict  )"%d\n", i);
#line 34
    i ++;
#line 34
    k ++;
  }
  }
#line 38
  printf((char const   * __restrict  )"Case7:\n");
#line 39
  i = 5;
  {
#line 40
  while (1) {
    vtrace0();
#line 40
    break;
#line 41
    printf((char const   * __restrict  )"%d\n", i);
#line 40
    i ++;
  }
  }
#line 44
  return (0);
}
}
